### ISSUE TITLE
[DXB/OMDB] GRP Stand Assignment Issue

### ISSUE THREAD

**Issue by DedpewlControl** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#13]
Seems like GRPlugin is assigning airlines that are not somewhat defined to Concourse A, B, C. Ideally all non-EK aircraft should be sent to Concourse D. Would it be possible to force everything that is non-EK and what not logically to Concourse D?

**Comment by luke11brown** [comment]
You mean non-EK aircraft should go to D stands?

Maybe I have my terminologies mixed up, but I would say it's semi realistic to send all unknown airlines to T1, i.e. C stands? No?

**Comment by DedpewlControl** [comment]
Sorry, I wrote this in a bit of a rush. During a test (@Ranbi2Delta probably has a log file to test it with) it assigned a non-EK aircraft to Concourse C (F/B stands north or south of the Concourse on the very left) where it should have been sent to Concourse D i.e. C stands. 

![image](https://github.com/user-attachments/assets/f5b1ac8e-d48c-47fd-8b6c-f26e36bdfb83)

**Comment by luke11brown** [comment]
Unsure why, as the T3 stands are defined using CALLSIGN:

<img width="337" alt="image" src="https://github.com/user-attachments/assets/20e10a5e-c017-4f90-b0a3-5319a0cd6e85">

**Comment by DedpewlControl** [comment]
I'll let @Ranbi2Delta crosscheck this as he was the one that reported it. I'll investigate this further.

**Comment by Ranbi2Delta** [comment]
I have a possible fix for this using the NOTCALLSIGN and lower priority duplicates of the stands. Will test and report back.

**Comment by Ranbi2Delta** [comment]
> Unsure why, as the T3 stands are defined using CALLSIGN:
> 
> <img alt="image" width="337" src="https://private-user-images.githubusercontent.com/13762210/361194925-20e10a5e-c017-4f90-b0a3-5319a0cd6e85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDM5NjcsIm5iZiI6MTcyNDc0MzY2NywicGF0aCI6Ii8xMzc2MjIxMC8zNjExOTQ5MjUtMjBlMTBhNWUtYzAxNy00ZjkwLWIwYTMtNTMxOWEwY2Q2ZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNTEyMWFhZDVmNWQwYmY5M2JhMDRjMGFhZDZjMDM3YTIyOGI3MjJmZjY4NGVkZWRmMjM4MDZiNTdkOTJhYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vtMluPy5fucRBaIixC2ESeNRg4hv_gt-Ni4i2uotLdY">
> Should be noted though, ACA, QFA and UAL all use T3. So I guess it was one of those?

Negative, it was some kind of Virtual Airline, don't remember the name right now

**Comment by Ranbi2Delta** [comment]
Attempted a fix at this using the "COPY" and "NOTCALLSIGN" functions.

**Comment by Ranbi2Delta** [comment]
Hopefully should be fixed now, including correct assignment of EK Cargo flights.
