### ISSUE TITLE
[SHJ/OMSJ] GRPlugin Config and Ground Layout

### ISSUE THREAD

**Issue by Ranbi2Delta** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#17]
GRPlugin Config and Ground Layout needs to be built.

**Comment by DedpewlControl** [comment]
Currently being reworked via QGIS.

**Comment by Ranbi2Delta** [comment]
GRPlugin config has been started. Stand assignment rules are still pending

**Comment by Ranbi2Delta** [comment]
GRPlugin config completed. Awaiting ground layout conversion to GRPlugin.

**Comment by DedpewlControl** [comment]
![image](https://github.com/user-attachments/assets/6b38c475-aaa1-4b1a-bee7-9ee9e916ef07)
OMSJ SMGCS Redesign via QGIS completed. To be implemented in the next AIRAC cycle.

**Comment by DedpewlControl** [comment]
Just to add a note onto this the GRPlugin maps file needs to be configured too to include the closed taxiways which are blocked off but still have a centerline attached to it
