### ISSUE TITLE
[DWC/OMDW] GRPlugin Config and Ground Layout

### ISSUE THREAD

**Issue by Ranbi2Delta** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#18]
GRPlugin Config and Ground Layout needs to be built

**Comment by DedpewlControl** [comment]
![image](https://github.com/user-attachments/assets/6dcfcddf-f1cc-4d23-918c-b3f74679401b)
QGIS Layout completed.

**Comment by DedpewlControl** [comment]
![image](https://github.com/user-attachments/assets/11534e5a-f6e5-4979-a418-a5675ef87942)
Completed awaiting conversion to GRPlugin

**Comment by DedpewlControl** [comment]
Completed via 341d1c851dcecacffb9c65ce57ed62e9d9faf0d7
