### ISSUE TITLE
No Default positions for OMAA

### ISSUE THREAD

**Issue by blackshadez** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#27]
There are no default profiles for any OMAA positions in the Aerodrome or Terminal Abu Dhabi
![Screenshot 2024-09-16 231635](https://github.com/user-attachments/assets/9e017066-e67a-4438-8618-682307689b08)
![Screenshot 2024-09-16 231645](https://github.com/user-attachments/assets/5873f458-c9c1-474b-938e-365e2e19acef)

**Comment by Ranbi2Delta** [comment]
Fixed. The source has the correct files, however the profiles were not uploaded to GNG. New profiles have been uploaded and this should be sorted for the next release.
