### ISSUE TITLE
Controller feedback link INOP

### ISSUE THREAD

**Issue by Verbjimtim** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#28]
404 error with the Vats.im link, it looks like the link wasn't renued or was deleted...

the link provided: vats.im/me/uaefeedback

**Comment by DedpewlControl** [comment]
Yep aware Paul didn't upload my profiles (or maybe I didn't push it to the repo). New link is vats.im/arb/feedback

**Comment by Ranbi2Delta** [comment]
Fixed
