### ISSUE TITLE
[AUH/OMAA] Taxiway D @31L threshold is under construction as per chart and scenery

### ISSUE THREAD

**Issue by dsolesvik** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#32]
Taxiway D between D10 and C4 is under construction and is closed on both the chart and scenery. This is not reflected on scenery so I would like to ask for this to be implemented for the duration of the construction.

**Comment by Ranbi2Delta** [comment]
Needs to be implemented using GRPlugin.
