### ISSUE TITLE
OMAA Del Helper (Initial Climbs for different runways not correct)

### ISSUE THREAD

**Issue by blackshadez** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#37]
Initial Climbs from 31L/13R are 5000ft and 31R/13L 4000ft according to OMAA SOP 2.3.1. However the Del Helper shows CFL issue and corrects the initial climb to 4000ft also for 31L runway.

In the image below it only shows OK for acft cleared on 4000ft for 31L and CFL for the ones with 5000ft.

![image_2024-11-08_213226375](https://github.com/user-attachments/assets/83bf048f-bc71-4320-985b-6ec9ff4311dc)

**Comment by DedpewlControl** [comment]
#7

**Comment by DedpewlControl** [comment]
Removed. Initial climbs to follow the TopSky definitions.
