### ISSUE TITLE
DelHel CFL Assignment Broken

### ISSUE THREAD

**Issue by Ranbi2Delta** [Arabian-vACC/OMAE-U.A.E-FIR-Controller-Pack#7]
CFL assignment and flight plan validation isn't working as intended. Needs to be looked at.

**Comment by DedpewlControl** [comment]
Can you confirm that it works correctly with different initial climbs set per CID? Not sure if this is a thing with this version of DELHEL as last time it added a single initial climb to all the SIDs per fix.

**Comment by luke11brown** [comment]
<img width="586" alt="image" src="https://github.com/user-attachments/assets/d2b98db2-88d5-4306-b56c-0292d4e58aa2">

Only tested at OMDB, so only A40 seen

**Comment by DedpewlControl** [comment]
Yeah I think at AUH it might cause a bit of issues as one runway has 5000ft and the other has 4000ft. So that needs to be checked.

**Comment by Ranbi2Delta** [comment]
After testing today, doesn't seem to work properly for OMAA

**Comment by DedpewlControl** [comment]
Removed. Initial climbs to follow the TopSky definitions.
